89 add sound to click on object that isnt a customer
GOUStudios/COVerIt- pull request #151
Opened 2023-07-07 14:54 UTC by JuanJoseJ

Basically, I updated the ClickManager to handle the sound when doing a miss click. ONly for lvl1

2023-07-07 19:51 UTC, iSergioMejia requested changes
10/10 just fix that two things

2023-07-07 19:51 UTC, iSergioMejia commented on GameDesign/Assets/Scripts/Managers/ClickManager.cs
> +        audioSource.PlayOneShot(miss, 0.7f);
We need to remove this, otherwise it will also sound when we click a masked person, overlaying with the already existing sound

2023-07-07 19:51 UTC, iSergioMejia commented on GameDesign/Assets/Scripts/MonoBehaviours/BackgroundObjectMonoBehaviour.cs
Is this file being used? If not just delete it

2023-07-10 13:03 UTC, theenergici approved these changes

2023-07-10 13:19 UTC, merged