27 characters behaviour
GOUStudios/COVerIt- pull request #51
Opened 2023-06-09 23:32 UTC by theenergici

The fsm machine is done and now the states call the functions from to determine the behavior of characters.
The 4 base types defined by the enumerator are done. (Normal, runner, Dinosaur, Antimaskers)
the only missing parts are the audio clues.  and in case of implementation the quick maskers.

in my opinion the best approach would be to tackle those as new issues to keep working  on this sprint on integration

also added some needed functionalities to improve #21 now a new issue should be set to redo the spawning with the set prefabs instead of needing different ones for masked/unmasked. now a simple call to `customerMonobehaviour` customer.maskNPC(bool value)  should set it to have or  no the mask and the needed changed values that this implies.
N.B. that putting the mask on the character makes it do the got hit animation once. can be changed later.

2023-06-11 08:44 UTC, iSergioMejia requested changes
- The masked customers are not working well, they get "stuck" on the first waypoint the arrive after the spawner and fail to leave. On other branches this is not the case
- The masked customers have still the old mesh. 
- I can mask an antimasker w/out tasing him
- People that have been "demasked" by antimaskers still have the mask in their faces

2023-06-11 14:10 UTC, theenergici commented
> * The masked customers are not working well, they get "stuck" on the first waypoint the arrive after the spawner and fail to leave. On other branches this is not the case
> * The masked customers have still the old mesh.
> * I can mask an antimasker w/out tasing him
> * People that have been "demasked" by antimaskers still have the mask in their faces

checked, anti masker cannot be masked without being tazed. hard to see due to the white mask.
fixed the getting stuck in waypoints
demasked people are correctly demasked 
new prefabs were done for the masked customers

2023-06-13 16:46 UTC, Sebasgut1 approved these changes

2023-06-14 19:31 UTC, iSergioMejia approved these changes

2023-06-14 19:32 UTC, merged