64 play music in the game
GOUStudios/COVerIt- pull request #94
Opened 2023-06-22 15:56 UTC by JuanJoseJ

I added objects to play music on the UI scene and the Level1 scene. Everything is managed by a MonoBehaviour for background music.

2023-06-24 14:41 UTC, theenergici commented
it works nicely, i would just lower a bit the total volume. and the fade out i see the function is implemented but i dont see it being called.
maybe making it be a permanent object (dont destroy on load ) makes sense and make it handle the level music as well.

2023-06-26 16:09 UTC, theenergici requested changes
The music is not persistent between scenes (when going to the level select screen it abruptly stops).
The mute buttons are not functional, not the ones from the main menu nor the ones from the pause menu.

2023-06-26 19:41 UTC, iSergioMejia commented
> The music is not persistent between scenes (when going to the level select screen it abruptly stops). The mute buttons are not functional, not the ones from the main menu nor the ones from the pause menu.

The mute buttons are already reported in #72 , not the scope of this issue. We can use the fade out so it doesn't abruptly stops

2023-06-27 07:51 UTC, theenergici approved these changes

2023-06-27 07:56 UTC, merged